# KITTI stereo model for seq.00-02

#==============#
# Camera Model #
#==============#

Camera:
  name: "d435i"
  setup: "stereo"
  model: "perspective"

  fx: 422.3118896484375
  fy: 422.3118896484375
  cx: 423.2429504394531
  cy: 242.09890747070312

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  fps: 30.0
  cols: 848
  rows: 480
  focal_x_baseline: 21.1155944824
  depth_threshold: 40

  color_order: "Gray"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 12
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr: 0.53716571886
  redundant_obs_ratio_thr: 0.9

#========================#
# Initializer Parameters #
#========================#

Initializer:
  min_num_triangulated_pts: 100

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 1.2
  keyframe_line_width: 1
  graph_line_width: 2
  point_size: 2
  camera_size: 0.8
  camera_line_width: 3
  viewpoint_x: 0.0
  viewpoint_y: -300
  viewpoint_z: -0.1
  viewpoint_f: 2800
