run_slam:
  ros__parameters:
    publish_tf: true
    odom_frame: "odom"
    map_frame: "map"
    robot_base_frame: "base_footprint"
    camera_frame: "left_camera_optical_frame"
    odom2d:  true
    publish_keyframes: true
    transform_tolerance: 0.5
    mono_topic: "camera/image_raw"
    # stereo input
    left_topic: "stereo_camera/left/image_raw"
    right_topic: "stereo_camera/right/image_raw"
    # rgbd input
    color_topic: "camera/color/image_raw"
    depth_topic: "camera/depth/image_raw"

