# TUM-RGBD RGBD model for 01

#==============#
# Camera Model #
#==============#

Camera:
  name: "Realsense"
  setup: "RGBD"
  model: "perspective"

  fx: 380.5162048339844
  cx: 313.52069091796875
  fy: 380.0697021484375
  cy: 245.2825927734375

  k1: -0.056858766824007034
  k2: 0.06763485074043274
  p1: -0.00023915356723591685
  p2: 0.000795295462012291
  k3: -0.021087031811475754

  fps: 30.0
  cols: 640
  rows: 480
  focal_x_baseline: 40.0
  depth_threshold: 40.0

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800
  depthmap_factor: 1000.0 # Note: Set it to 1.0 for the rosbag format data set.

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr: 0.07471049682
  redundant_obs_ratio_thr: 0.9

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.05
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400